# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fuction.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fuction(object):
    def setupUi(self, Fuction):
        Fuction.setObjectName("Fuction")
        Fuction.resize(400, 400)
        Fuction.setWindowIcon(QtGui.QIcon("./icon/windowsicon.ico"))
        Fuction.setMinimumSize(QtCore.QSize(400, 400))
        Fuction.setMaximumSize(QtCore.QSize(400, 400))
        self.FixAssetBtn = QtWidgets.QPushButton(Fuction)
        self.FixAssetBtn.setGeometry(QtCore.QRect(125, 40, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FixAssetBtn.sizePolicy().hasHeightForWidth())
        self.FixAssetBtn.setSizePolicy(sizePolicy)
        self.FixAssetBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.FixAssetBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FixAssetBtn.setFont(font)
        self.FixAssetBtn.setObjectName("FixAssetBtn")
        self.SuppliesBtn = QtWidgets.QPushButton(Fuction)
        self.SuppliesBtn.setGeometry(QtCore.QRect(125, 110, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SuppliesBtn.sizePolicy().hasHeightForWidth())
        self.SuppliesBtn.setSizePolicy(sizePolicy)
        self.SuppliesBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.SuppliesBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SuppliesBtn.setFont(font)
        self.SuppliesBtn.setObjectName("SuppliesBtn")
        self.ScrapBtn = QtWidgets.QPushButton(Fuction)
        self.ScrapBtn.setGeometry(QtCore.QRect(125, 180, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ScrapBtn.sizePolicy().hasHeightForWidth())
        self.ScrapBtn.setSizePolicy(sizePolicy)
        self.ScrapBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.ScrapBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ScrapBtn.setFont(font)
        self.ScrapBtn.setObjectName("ScrapBtn")
        self.PurchaseBtn = QtWidgets.QPushButton(Fuction)
        self.PurchaseBtn.setGeometry(QtCore.QRect(125, 250, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PurchaseBtn.sizePolicy().hasHeightForWidth())
        self.PurchaseBtn.setSizePolicy(sizePolicy)
        self.PurchaseBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.PurchaseBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PurchaseBtn.setFont(font)
        self.PurchaseBtn.setObjectName("PurchaseBtn")
        self.DeviceBtn = QtWidgets.QPushButton(Fuction)
        self.DeviceBtn.setGeometry(QtCore.QRect(125, 320, 150, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeviceBtn.sizePolicy().hasHeightForWidth())
        self.DeviceBtn.setSizePolicy(sizePolicy)
        self.DeviceBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.DeviceBtn.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DeviceBtn.setFont(font)
        self.DeviceBtn.setObjectName("DeviceBtn")
        self.retranslateUi(Fuction)
        QtCore.QMetaObject.connectSlotsByName(Fuction)

    def retranslateUi(self, Fuction):
        _translate = QtCore.QCoreApplication.translate
        Fuction.setWindowTitle(_translate("Fuction", "模块选择"))
        self.FixAssetBtn.setText(_translate("Fuction", "固定资产"))
        self.SuppliesBtn.setText(_translate("Fuction", "耗材管理"))
        self.ScrapBtn.setText(_translate("Fuction", "报废管理"))
        self.PurchaseBtn.setText(_translate("Fuction", "采购中"))
        self.DeviceBtn.setText(_translate("Fuction", "设备信息管理(IT)"))

