# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fixasset.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FixAsset(object):
    def setupUi(self, FixAsset):
        FixAsset.setObjectName("FixAsset")
        FixAsset.resize(750, 700)
        FixAsset.setMinimumSize(QtCore.QSize(750, 700))
        FixAsset.setMaximumSize(QtCore.QSize(750, 700))
        FixAsset.setWindowIcon(QtGui.QIcon("./icon/windowsicon.ico"))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FixAsset.sizePolicy().hasHeightForWidth())
        FixAsset.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(FixAsset)
        self.centralwidget.setObjectName("centralwidget")
        self.Fixassetno_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Fixassetno_LineEdit.setGeometry(QtCore.QRect(390, 220, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fixassetno_LineEdit.sizePolicy().hasHeightForWidth())
        self.Fixassetno_LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Fixassetno_LineEdit.setFont(font)
        self.Fixassetno_LineEdit.setObjectName("Fixassetno_LineEdit")
        self.Isscra_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Isscra_LineEdit.setGeometry(QtCore.QRect(390, 175, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Isscra_LineEdit.sizePolicy().hasHeightForWidth())
        self.Isscra_LineEdit.setSizePolicy(sizePolicy)
        self.Isscra_LineEdit.setObjectName("Isscra_LineEdit")
        self.Dept_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Dept_LineEdit.setGeometry(QtCore.QRect(390, 40, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dept_LineEdit.sizePolicy().hasHeightForWidth())
        self.Dept_LineEdit.setSizePolicy(sizePolicy)
        self.Dept_LineEdit.setObjectName("Dept_LineEdit")
        self.Servicetag_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Servicetag_LineEdit.setGeometry(QtCore.QRect(120, 220, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Servicetag_LineEdit.sizePolicy().hasHeightForWidth())
        self.Servicetag_LineEdit.setSizePolicy(sizePolicy)
        self.Servicetag_LineEdit.setObjectName("Servicetag_LineEdit")
        self.Getdate_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Getdate_LineEdit.setGeometry(QtCore.QRect(390, 130, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Getdate_LineEdit.sizePolicy().hasHeightForWidth())
        self.Getdate_LineEdit.setSizePolicy(sizePolicy)
        self.Getdate_LineEdit.setObjectName("Getdate_LineEdit")
        self.Config_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Config_LineEdit.setGeometry(QtCore.QRect(390, 85, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Config_LineEdit.sizePolicy().hasHeightForWidth())
        self.Config_LineEdit.setSizePolicy(sizePolicy)
        self.Config_LineEdit.setObjectName("Config_LineEdit")
        self.Name_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Name_LineEdit.setGeometry(QtCore.QRect(120, 40, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Name_LineEdit.sizePolicy().hasHeightForWidth())
        self.Name_LineEdit.setSizePolicy(sizePolicy)
        self.Name_LineEdit.setObjectName("Name_LineEdit")
        self.Location_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Location_LineEdit.setGeometry(QtCore.QRect(120, 175, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Location_LineEdit.sizePolicy().hasHeightForWidth())
        self.Location_LineEdit.setSizePolicy(sizePolicy)
        self.Location_LineEdit.setObjectName("Location_LineEdit")
        self.User_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.User_LineEdit.setGeometry(QtCore.QRect(120, 130, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.User_LineEdit.sizePolicy().hasHeightForWidth())
        self.User_LineEdit.setSizePolicy(sizePolicy)
        self.User_LineEdit.setObjectName("User_LineEdit")
        self.Model_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Model_LineEdit.setGeometry(QtCore.QRect(120, 85, 120, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Model_LineEdit.sizePolicy().hasHeightForWidth())
        self.Model_LineEdit.setSizePolicy(sizePolicy)
        self.Model_LineEdit.setObjectName("Model_LineEdit")
        self.Fixassetno_Label = QtWidgets.QLabel(self.centralwidget)
        self.Fixassetno_Label.setGeometry(QtCore.QRect(280, 220, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Fixassetno_Label.sizePolicy().hasHeightForWidth())
        self.Fixassetno_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Fixassetno_Label.setFont(font)
        self.Fixassetno_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Fixassetno_Label.setObjectName("Fixassetno_Label")
        self.Model_Label = QtWidgets.QLabel(self.centralwidget)
        self.Model_Label.setGeometry(QtCore.QRect(10, 85, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Model_Label.sizePolicy().hasHeightForWidth())
        self.Model_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Model_Label.setFont(font)
        self.Model_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Model_Label.setObjectName("Model_Label")
        self.User_Label = QtWidgets.QLabel(self.centralwidget)
        self.User_Label.setGeometry(QtCore.QRect(10, 130, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.User_Label.sizePolicy().hasHeightForWidth())
        self.User_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.User_Label.setFont(font)
        self.User_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.User_Label.setObjectName("User_Label")
        self.Location_Label = QtWidgets.QLabel(self.centralwidget)
        self.Location_Label.setGeometry(QtCore.QRect(10, 175, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Location_Label.sizePolicy().hasHeightForWidth())
        self.Location_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Location_Label.setFont(font)
        self.Location_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Location_Label.setObjectName("Location_Label")
        self.Servicetag_Label = QtWidgets.QLabel(self.centralwidget)
        self.Servicetag_Label.setGeometry(QtCore.QRect(10, 220, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Servicetag_Label.sizePolicy().hasHeightForWidth())
        self.Servicetag_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Servicetag_Label.setFont(font)
        self.Servicetag_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Servicetag_Label.setObjectName("Servicetag_Label")
        self.Name_Label = QtWidgets.QLabel(self.centralwidget)
        self.Name_Label.setGeometry(QtCore.QRect(10, 40, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Name_Label.sizePolicy().hasHeightForWidth())
        self.Name_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Name_Label.setFont(font)
        self.Name_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Name_Label.setObjectName("Name_Label")
        self.Dept_Label = QtWidgets.QLabel(self.centralwidget)
        self.Dept_Label.setGeometry(QtCore.QRect(280, 40, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Dept_Label.sizePolicy().hasHeightForWidth())
        self.Dept_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Dept_Label.setFont(font)
        self.Dept_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Dept_Label.setObjectName("Dept_Label")
        self.Config_Label = QtWidgets.QLabel(self.centralwidget)
        self.Config_Label.setGeometry(QtCore.QRect(280, 85, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Config_Label.sizePolicy().hasHeightForWidth())
        self.Config_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Config_Label.setFont(font)
        self.Config_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Config_Label.setObjectName("Config_Label")
        self.Getdate_Label = QtWidgets.QLabel(self.centralwidget)
        self.Getdate_Label.setGeometry(QtCore.QRect(280, 130, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Getdate_Label.sizePolicy().hasHeightForWidth())
        self.Getdate_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Getdate_Label.setFont(font)
        self.Getdate_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Getdate_Label.setObjectName("Getdate_Label")
        self.Isscra_Label = QtWidgets.QLabel(self.centralwidget)
        self.Isscra_Label.setGeometry(QtCore.QRect(280, 175, 105, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Isscra_Label.sizePolicy().hasHeightForWidth())
        self.Isscra_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Isscra_Label.setFont(font)
        self.Isscra_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Isscra_Label.setObjectName("Isscra_Label")
        self.QueryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.QueryBtn.setGeometry(QtCore.QRect(560, 120, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QueryBtn.sizePolicy().hasHeightForWidth())
        self.QueryBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.QueryBtn.setFont(font)
        self.QueryBtn.setObjectName("QueryBtn")
        self.Data_TableView = QtWidgets.QTableView(self.centralwidget)
        self.Data_TableView.setGeometry(QtCore.QRect(10, 270, 730, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Data_TableView.sizePolicy().hasHeightForWidth())
        self.Data_TableView.setSizePolicy(sizePolicy)
        self.Data_TableView.setSizeIncrement(QtCore.QSize(0, 0))
        self.Data_TableView.setWordWrap(True);
        self.Data_TableView.setSortingEnabled(True)
        self.Data_TableView.setShowGrid(True)
        self.Data_TableView.setObjectName("Data_TableView")
        self.ClearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ClearBtn.setGeometry(QtCore.QRect(670, 250, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearBtn.sizePolicy().hasHeightForWidth())
        self.ClearBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ClearBtn.setFont(font)
        self.ClearBtn.setObjectName("ClearBtn")
        self.Sub_ModifyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.Sub_ModifyBtn.setGeometry(QtCore.QRect(0, 0, 60, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sub_ModifyBtn.sizePolicy().hasHeightForWidth())
        self.Sub_ModifyBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Sub_ModifyBtn.setFont(font)
        self.Sub_ModifyBtn.setObjectName("Sub_ModifyBtn")
        FixAsset.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FixAsset)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        FixAsset.setMenuBar(self.menubar)
        self.Fixasset_Statusbar = QtWidgets.QStatusBar(FixAsset)
        self.Fixasset_Statusbar.setObjectName("Fixasset_Statusbar")
        FixAsset.setStatusBar(self.Fixasset_Statusbar)
        self.LineEditaction = QtWidgets.QAction(FixAsset)
        self.LineEditaction.setObjectName("LineEditaction")
        self.Addlineaction = QtWidgets.QAction(FixAsset)
        self.Addlineaction.setObjectName("Addlineaction")
        self.printaction = QtWidgets.QAction(FixAsset)
        self.printaction.setObjectName("printaction")
        self.menu.addAction(self.printaction)
        self.menubar.addAction(self.menu.menuAction())
        self.retranslateUi(FixAsset)
        QtCore.QMetaObject.connectSlotsByName(FixAsset)

    def retranslateUi(self, FixAsset):
        _translate = QtCore.QCoreApplication.translate
        FixAsset.setWindowTitle(_translate("FixAsset", "固定资产"))
        self.Fixassetno_Label.setText(_translate("FixAsset", "固定资产编号："))
        self.Model_Label.setText(_translate("FixAsset", "型号："))
        self.User_Label.setText(_translate("FixAsset", "使用者："))
        self.Location_Label.setText(_translate("FixAsset", "安装位置："))
        self.Servicetag_Label.setText(_translate("FixAsset", "ServiceTag："))
        self.Name_Label.setText(_translate("FixAsset", "名称："))
        self.Dept_Label.setText(_translate("FixAsset", "部门："))
        self.Config_Label.setText(_translate("FixAsset", "配置："))
        self.Getdate_Label.setText(_translate("FixAsset", "到货日期："))
        self.Isscra_Label.setText(_translate("FixAsset", "是否报废："))
        self.QueryBtn.setText(_translate("FixAsset", "查询"))
        self.ClearBtn.setText(_translate("FixAsset", "清除"))
        self.Sub_ModifyBtn.setText(_translate("FixAsset", "提交修改"))
        self.menu.setTitle(_translate("FixAsset", "文件"))
        self.LineEditaction.setText(_translate("FixAsset", "行编辑"))
        self.LineEditaction.setToolTip(_translate("FixAsset", "LineEditaction"))
        self.Addlineaction.setText(_translate("FixAsset", "添加行"))
        self.Addlineaction.setToolTip(_translate("FixAsset", "Addlineaction"))
        self.printaction.setText(_translate("FixAsset", "打印"))


