# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logonwin.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logon(object):
    def setupUi(self, Logon):
        Logon.setObjectName("Logon")
        Logon.setWindowModality(QtCore.Qt.NonModal)
        Logon.resize(300, 300)
        Logon.setMinimumSize(QtCore.QSize(300, 300))
        Logon.setMaximumSize(QtCore.QSize(300, 300))
        Logon.setWindowIcon(QtGui.QIcon("./icon/windowsicon.ico"))
        self.centralwidget = QtWidgets.QWidget(Logon)
        self.centralwidget.setObjectName("centralwidget")
        self.LogonBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LogonBtn.setGeometry(QtCore.QRect(115, 240, 70, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogonBtn.sizePolicy().hasHeightForWidth())
        self.LogonBtn.setSizePolicy(sizePolicy)
        self.LogonBtn.setMinimumSize(QtCore.QSize(70, 20))
        self.LogonBtn.setMaximumSize(QtCore.QSize(70, 20))
        self.LogonBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LogonBtn.setObjectName("LogonBtn")
        self.LogonBtn.setToolTip('Pls. click to login')
        self.Username_Label = QtWidgets.QLabel(self.centralwidget)
        self.Username_Label.setEnabled(True)
        self.Username_Label.setGeometry(QtCore.QRect(75, 185, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Username_Label.setFont(font)
        self.Username_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Username_Label.setObjectName("Username_Label")
        self.Password_Label = QtWidgets.QLabel(self.centralwidget)
        self.Password_Label.setGeometry(QtCore.QRect(75, 210, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_Label.setFont(font)
        self.Password_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_Label.setObjectName("Password_Label")
        self.AppName_Label = QtWidgets.QLabel(self.centralwidget)
        self.AppName_Label.setGeometry(QtCore.QRect(75, 10, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.AppName_Label.setFont(font)
        self.AppName_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.AppName_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.AppName_Label.setLineWidth(1)
        self.AppName_Label.setTextFormat(QtCore.Qt.PlainText)
        self.AppName_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.AppName_Label.setObjectName("AppName_Label")
        self.GST_logo_Label = QtWidgets.QLabel(self.centralwidget)
        self.GST_logo_Label.setGeometry(QtCore.QRect(75, 45, 150, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GST_logo_Label.sizePolicy().hasHeightForWidth())
        self.GST_logo_Label.setSizePolicy(sizePolicy)
        self.GST_logo_Label.setMinimumSize(QtCore.QSize(150, 100))
        self.GST_logo_Label.setMaximumSize(QtCore.QSize(150, 100))
        self.GST_logo_Label.setText("")
        self.GST_logo_Label.setPixmap(QtGui.QPixmap(":/Img/GST_Logo.png"))
        self.GST_logo_Label.setScaledContents(True)
        self.GST_logo_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.GST_logo_Label.setObjectName("GST_logo_Label")
        self.Username_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Username_LineEdit.setGeometry(QtCore.QRect(145, 185, 80, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Username_LineEdit.sizePolicy().hasHeightForWidth())
        self.Username_LineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Username_LineEdit.setFont(font)
        self.Username_LineEdit.setToolTip('Pls. Input Username')
        self.Username_LineEdit.setMouseTracking(True)
        self.Username_LineEdit.setTabletTracking(False)
        self.Username_LineEdit.setText("")
        self.Username_LineEdit.setFrame(True)
        self.Username_LineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Username_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Username_LineEdit.setClearButtonEnabled(False)
        self.Username_LineEdit.setObjectName("Username_LineEdit")
        self.Password_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Password_LineEdit.setGeometry(QtCore.QRect(145, 210, 80, 20))
        self.Password_LineEdit.setToolTip('Pls. Input Password')
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Password_LineEdit.sizePolicy().hasHeightForWidth())
        self.Password_LineEdit.setSizePolicy(sizePolicy)
        self.Password_LineEdit.setText("")
        self.Password_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.Password_LineEdit.setClearButtonEnabled(True)
        self.Password_LineEdit.setObjectName("Password_LineEdit")
        self.Logontxt_Label = QtWidgets.QLabel(self.centralwidget)
        self.Logontxt_Label.setGeometry(QtCore.QRect(80, 260, 140, 16))
        self.Logontxt_Label.setText("")
        self.Logontxt_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Logontxt_Label.setObjectName("Logontxt_Label")
        Logon.setCentralWidget(self.centralwidget)
        self.retranslateUi(Logon)
        QtCore.QMetaObject.connectSlotsByName(Logon)

    def retranslateUi(self, Logon):
        _translate = QtCore.QCoreApplication.translate
        Logon.setWindowTitle(_translate("Logon", "GST IT管理系统"))
        self.LogonBtn.setText(_translate("Logon", "登陆"))
        self.Username_Label.setText(_translate("Logon", "Username:"))
        self.Password_Label.setText(_translate("Logon", "Password:"))
        self.AppName_Label.setText(_translate("Logon", "GST IT管理系统"))

import apprcc_rc
